name: CMake

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt update && sudo apt install -y ninja-build ccache cppcheck

    - name: Configure CMake
      run: cmake --preset develop ./

    - name: Build
      run: cmake --build ./ --preset develop

    - name: Test
      run: ctest --preset develop_tests

    - name: Coverage
      run: cmake --build . --preset coverage
      
    - name: Extract coverage
      run: echo "COVERAGE=$(cat build/generate_report.xml | grep line-rate | awk -F '"' '{print int($2 * 100)}')%" >> $GITHUB_ENV
    
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GISTS_API_KEY }}
        gistID: b7156fe3db753fc241ad820cfe0a3566
        filename: dev_badge.json
        label: Coverage
        message: ${{ env.COVERAGE }}
        color: grey
      
